/* =========================================================================
   JIYA — BASIC BUSINESS INFO  (set ONCE during setup)
   =========================================================================

   This has your business name, contact details, and the intro text.
   These rarely change, so they're set once at setup and then left alone.

   >>> To add or change PRODUCTS, you do NOT edit this file. <<<
   >>> You add products in the Airtable app. See HOW-TO-ADD-PRODUCTS.md <<<
   ========================================================================= */

window.JIYA = {

  business: {
    name: "Jiya Handmade Creations",
    tagline: "Handmade with love, made just for you.",
    location: "Guntur, Andhra Pradesh",
    instagram: "jiya_handmade_creations",         // without the @
    instagramUrl: "https://www.instagram.com/jiya_handmade_creations/",
    whatsapp: "919980687834",                      // country code + number, no + or spaces
  },

  hero: {
    heading: "Hand-knitted with love",
    subheading:
      "Small-batch woollen crochet, pouches, charms and caps — each one made " +
      "by hand in Guntur, made just for you.",
    buttonText: "See our creations",
  },

  about: {
    heading: "Our Story",
    text:
      "Jiya Handmade Creations is a small, handmade woollen brand from Guntur. " +
      "Every piece — from festive crochet rakhis to cosy caps — is knitted and " +
      "crocheted by hand, in limited batches, with care in every stitch. " +
      "We made our debut this Rakhi season and sold out two days early. " +
      "Thank you for being part of the journey.",
  },

  /* -------------------------------------------------------------------------
     SAMPLE PRODUCTS — shown only until Airtable is connected (config.js).
     Once Airtable is connected, real products come from there and these are
     ignored. You don't need to edit these.
     ------------------------------------------------------------------------- */
  sampleProducts: [
    { name: "Crochet Rakhi", category: "Crochet", price: "From ₹80",
      description: "Handmade woollen rakhi in festive colours.", image: "", soldOut: true, featured: false },
    { name: "Woollen Mobile Pouch", category: "Pouches", price: "From ₹200",
      description: "Snug, hand-knitted pouch for your phone. Custom colours available.", image: "", soldOut: false, featured: true },
    { name: "Bag & Mobile Charm", category: "Charms", price: "From ₹60",
      description: "Little crochet hangings for your bag or phone.", image: "", soldOut: false, featured: false },
    { name: "Hand-Knitted Woollen Cap", category: "Caps", price: "From ₹250",
      description: "Warm, soft caps for babies, kids and adults.", image: "", soldOut: false, featured: true },
  ],

};
