/* =========================================================================
   JIYA — BASIC BUSINESS INFO  (set ONCE during setup)
   =========================================================================

   This has your business name, contact details, and the intro text.
   These rarely change, so they're set once at setup and then left alone.

   >>> To add or change PRODUCTS, you do NOT edit this file. <<<
   >>> You add products in the Airtable app. See HOW-TO-ADD-PRODUCTS.md <<<
   ========================================================================= */

window.JIYA = {

  business: {
    name: "Jiya Handmade Creations",
    tagline: "Handmade with love, made just for you.",
    location: "Guntur, Andhra Pradesh",
    instagram: "jiya_handmade_creations",         // without the @
    instagramUrl: "https://www.instagram.com/jiya_handmade_creations/",
    whatsapp: "919980687834",                      // country code + number, no + or spaces
  },

  hero: {
    heading: "Hand-knitted with love",
    subheading:
      "Small-batch woollen crochet, pouches, charms and caps — each one made " +
      "by hand in Guntur, made just for you.",
    buttonText: "See our creations",
  },

  about: {
    heading: "Our Story",
    text:
      "Jiya Handmade Creations is a small, handmade woollen brand from Guntur. " +
      "Every piece — from festive crochet rakhis to cosy caps — is knitted and " +
      "crocheted by hand, in limited batches, with care in every stitch. " +
      "We made our debut this Rakhi season and sold out two days early. " +
      "Thank you for being part of the journey.",
  },

  /* -------------------------------------------------------------------------
     SAMPLE PRODUCTS — shown only until Airtable is connected (config.js).
     Once Airtable is connected, real products come from there and these are
     ignored. You don't need to edit these.
     ------------------------------------------------------------------------- */
  sampleProducts: [
    { name: "Crochet Rakhi", category: "Festive", price: "From ₹80",
      description: "Handmade woollen rakhi in festive colours.", image: "", soldOut: true, featured: false,
      status: "shop", collection: "Rakhi 2026", date: "2026-08-01" },
    { name: "Woollen Mobile Pouch", category: "Pouches", price: "From ₹200",
      description: "Snug, hand-knitted pouch for your phone. Custom colours available.", image: "", soldOut: false, featured: true,
      status: "shop", collection: "", date: "" },
    { name: "AirPods Pouch", category: "Pouches", price: "From ₹180",
      description: "Cosy little pouch to keep your earbuds safe.", image: "", soldOut: false, featured: false },
    { name: "Bag & Mobile Charm", category: "Charms & Keychains", price: "From ₹60",
      description: "Little crochet hangings for your bag or phone.", image: "", soldOut: false, featured: false },
    { name: "Crochet Keychain", category: "Charms & Keychains", price: "From ₹70",
      description: "Handmade keychains in fun shapes and colours.", image: "", soldOut: false, featured: false },
    { name: "Woollen Scrunchie", category: "Hair Accessories", price: "From ₹50",
      description: "Soft, gentle scrunchies hand-crocheted in pretty shades.", image: "", soldOut: false, featured: true },
    { name: "Hand-Knitted Cap", category: "Caps & Beanies", price: "From ₹250",
      description: "Warm, soft caps for babies, kids and adults.", image: "", soldOut: false, featured: false },
    { name: "Woollen Beanie", category: "Caps & Beanies", price: "From ₹280",
      description: "Snug beanie to keep you warm in style.", image: "", soldOut: false, featured: false },
    { name: "Mittens & Gloves", category: "Winterwear", price: "From ₹220",
      description: "Hand-knitted mittens and gloves for chilly days.", image: "", soldOut: false, featured: false },
    { name: "Crochet Toy", category: "Toys", price: "From ₹150",
      description: "Adorable handmade soft toys — small, medium and large.", image: "", soldOut: false, featured: true },
    { name: "Infant Booties", category: "Baby", price: "From ₹160",
      description: "Tiny, soft woollen shoes for little feet.", image: "", soldOut: false, featured: false },
  ],

};
